package Telas;


import Telas.telaCadastroProduto;
import Telas.telaCadastroServiço;
import Telas.telaConsultaClientes;
import Telas.telaConsultaServiços;
import Telas.telaConsultaProdutos;
import Telas.telaCadastroCliente;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LEANDRACRUZDELEMOS
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPainel = new javax.swing.JPanel();
        btnCliente = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnProduto = new javax.swing.JButton();
        btnsair = new javax.swing.JButton();
        desktopPrincipal = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemCliente = new javax.swing.JMenuItem();
        itemProduto = new javax.swing.JMenuItem();
        itemServiço = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemClientes = new javax.swing.JMenuItem();
        itemProdutos = new javax.swing.JMenuItem();
        itemServiços = new javax.swing.JMenuItem();
        itemNovoPedido = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemRelatorioCliente = new javax.swing.JMenuItem();
        itemRelatorioOrdemdeServiço = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        itemJanelas = new javax.swing.JMenu();
        itemMinimizarTodas = new javax.swing.JMenu();
        itemRestaurarTodas = new javax.swing.JMenu();
        itemLadoALado = new javax.swing.JMenu();
        itemEmCascata = new javax.swing.JMenu();
        itemEmGrade = new javax.swing.JMenu();
        itemFecharTodas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPainel.setBackground(new java.awt.Color(102, 0, 102));

        btnCliente.setToolTipText("Acessar seu perfil como cliente");
        btnCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCliente.setName("btnCliente"); // NOI18N

        btnPedido.setToolTipText("Fazer um novo pedido");
        btnPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPedido.setName("btnPedidos"); // NOI18N

        btnProduto.setToolTipText("Acompanhar um produto");
        btnProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProduto.setName("btnProduto"); // NOI18N
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        btnsair.setToolTipText("Sair do sistema");
        btnsair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnsair.setName("btnSair"); // NOI18N
        btnsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPrincipalLayout = new javax.swing.GroupLayout(desktopPrincipal);
        desktopPrincipal.setLayout(desktopPrincipalLayout);
        desktopPrincipalLayout.setHorizontalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        desktopPrincipalLayout.setVerticalGroup(
            desktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btnPainelLayout = new javax.swing.GroupLayout(btnPainel);
        btnPainel.setLayout(btnPainelLayout);
        btnPainelLayout.setHorizontalGroup(
            btnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPainelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(btnsair, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(desktopPrincipal)
        );
        btnPainelLayout.setVerticalGroup(
            btnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPainelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(btnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(btnPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPainelLayout.createSequentialGroup()
                            .addComponent(btnsair)
                            .addGap(8, 8, 8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPrincipal))
        );

        jMenu1.setText("Cadastro");

        itemCliente.setText("Cliente");
        itemCliente.setName("itemCliente"); // NOI18N
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        jMenu1.add(itemCliente);

        itemProduto.setText("Produto");
        itemProduto.setName("itemProduto"); // NOI18N
        itemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(itemProduto);

        itemServiço.setText("Serviço");
        itemServiço.setName("itemServico"); // NOI18N
        itemServiço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemServiçoActionPerformed(evt);
            }
        });
        jMenu1.add(itemServiço);

        menuPrincipal.add(jMenu1);

        jMenu2.setText("Consulta");

        itemClientes.setText("Clientes");
        jMenu2.add(itemClientes);

        itemProdutos.setText("Produtos");
        jMenu2.add(itemProdutos);

        itemServiços.setText("Serviços");
        itemServiços.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemServiçosActionPerformed(evt);
            }
        });
        jMenu2.add(itemServiços);

        menuPrincipal.add(jMenu2);

        itemNovoPedido.setText("Pedidos");

        jMenuItem7.setText("Novo Pedido");
        itemNovoPedido.add(jMenuItem7);

        menuPrincipal.add(itemNovoPedido);

        jMenu4.setText("Relátorio");

        itemRelatorioCliente.setText("Cliente");
        itemRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRelatorioClienteActionPerformed(evt);
            }
        });
        jMenu4.add(itemRelatorioCliente);

        itemRelatorioOrdemdeServiço.setText("Serviço");
        jMenu4.add(itemRelatorioOrdemdeServiço);

        jMenuItem10.setText("Ordem de Serviço");
        jMenu4.add(jMenuItem10);

        menuPrincipal.add(jMenu4);

        jMenu5.setText("Utilitário");
        menuPrincipal.add(jMenu5);

        jMenu6.setText("Sobre");
        menuPrincipal.add(jMenu6);

        jMenu7.setText("Ajuda");
        menuPrincipal.add(jMenu7);

        itemJanelas.setText("Janelas");

        itemMinimizarTodas.setText("Minimizar todas");
        itemJanelas.add(itemMinimizarTodas);

        itemRestaurarTodas.setText("Restaurar todas");
        itemJanelas.add(itemRestaurarTodas);

        itemLadoALado.setText("Lado a lado verticalmente");
        itemJanelas.add(itemLadoALado);

        itemEmCascata.setText("Em cascata");
        itemJanelas.add(itemEmCascata);

        itemEmGrade.setText("Em grade");
        itemJanelas.add(itemEmGrade);

        itemFecharTodas.setText("Fechar todas");
        itemJanelas.add(itemFecharTodas);

        menuPrincipal.add(itemJanelas);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsairActionPerformed

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void itemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProdutoActionPerformed
       telaCadastroProduto tela = new telaCadastroProduto();
       desktopPrincipal.add(tela);
       tela.setVisible(true);
    }//GEN-LAST:event_itemProdutoActionPerformed

    private void itemServiçosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServiçosActionPerformed
       telaConsultaServiços tela = new telaConsultaServiços();
       desktopPrincipal.add(tela);
       tela.setVisible(true);
    }//GEN-LAST:event_itemServiçosActionPerformed

    private void itemRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRelatorioClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemRelatorioClienteActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
       telaCadastroCliente tela = new telaCadastroCliente();
       desktopPrincipal.add(tela);
       tela.setVisible(true);
    }//GEN-LAST:event_itemClienteActionPerformed

    private void itemServiçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServiçoActionPerformed
       telaCadastroServiço tela = new telaCadastroServiço();
       desktopPrincipal.add(tela);
       tela.setVisible(true);
    }//GEN-LAST:event_itemServiçoActionPerformed

    private void itemClientesActionPerformed(java.awt.event.ActionEvent evt) {                                            
       telaConsultaClientes tela = new telaConsultaClientes();
       desktopPrincipal.add(tela);
       tela.setVisible(true);
    }    
    
    private void itemProdutosActionPerformed(java.awt.event.ActionEvent evt) {                                            
       telaConsultaProdutos tela = new telaConsultaProdutos();
       desktopPrincipal.add(tela);
       tela.setVisible(true);
    }    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JPanel btnPainel;
    private javax.swing.JButton btnPedido;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnsair;
    private javax.swing.JDesktopPane desktopPrincipal;
    private javax.swing.JMenuItem itemCliente;
    private javax.swing.JMenuItem itemClientes;
    private javax.swing.JMenu itemEmCascata;
    private javax.swing.JMenu itemEmGrade;
    private javax.swing.JMenu itemFecharTodas;
    private javax.swing.JMenu itemJanelas;
    private javax.swing.JMenu itemLadoALado;
    private javax.swing.JMenu itemMinimizarTodas;
    private javax.swing.JMenu itemNovoPedido;
    private javax.swing.JMenuItem itemProduto;
    private javax.swing.JMenuItem itemProdutos;
    private javax.swing.JMenuItem itemRelatorioCliente;
    private javax.swing.JMenuItem itemRelatorioOrdemdeServiço;
    private javax.swing.JMenu itemRestaurarTodas;
    private javax.swing.JMenuItem itemServiço;
    private javax.swing.JMenuItem itemServiços;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
